# Ordered by output of `jazzy — help config`

output: CardCrucible_Docs

clean: true

xcodebuild_arguments:
- -workspace
- CardCrucible.xcworkspace
- -scheme
- CardCrucible
- CODE_SIGNING_ALLOWED = NO

author: Matthew Kressin

module: CardCrucible

module_version: 1.0

copyright: Copyright message here

readme: README.md 

min_acl: internal

# Options : [apple | fullwidth | jony | DIRPATH]

# Which theme to use. Specify either ‘apple’ (default), one of the other built-in theme names, or the path to your mustache templates and other assets for a custom theme.Default: apple

theme: apple
